WITH INFO AS (
  SELECT I.REST_ID
       , I.REST_NAME
       , I.FOOD_TYPE
       , I.FAVORITES
       , I.ADDRESS
    FROM REST_INFO I
    WHERE I.ADDRESS LIKE '서울%'
), REVIEW AS (
  SELECT R.REST_ID
       , ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW R
    GROUP BY R.REST_ID
)
SELECT I.*
     , R.SCORE
  FROM INFO I
  JOIN REVIEW R ON R.REST_ID = I.REST_ID
 ORDER BY R.SCORE DESC, I.FAVORITES DESC 