-- 코드를 입력하세요
SELECT T.TITLE, T.BOARD_ID, C.REPLY_ID, C.WRITER_ID, C.CONTENTS, DATE_FORMAT(C.CREATED_DATE, '%Y-%m-%d') CREATED_DATE FROM USED_GOODS_BOARD T, USED_GOODS_REPLY C
WHERE C.BOARD_ID=T.BOARD_ID
AND T.CREATED_DATE LIKE '2022-10%' 
ORDER BY CREATED_DATE ASC, T.TITLE ASC